### ISSUE TITLE
[Failed] Send email

### ISSUE THREAD

**Issue by s8w1e2ep** [USCC-LAB/Weekly#3]
I send email via "smtp.py", but it is failed.
I found this problem may about gmail secure level.
My gmail needs two-stage certification, so I change another gmail account.
And then, it is success.

**Comment by iankuan** [comment]
Could you provide the error message or trackback, please? More question about the configuration of Gmail, do you turn on IMAP? Probably, you could try to turn on the option which accepts the low-security apps.

**Comment by s8w1e2ep** [comment]
**SMTPAuthenticationError(code, resp)**
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted.
Learn more at\n5.7.8
https://support.google.com/mail/?p=BadCredentials s67sm4462446pgb.13 - gsmtp')

**Comment by iankuan** [comment]
I've confirmed that it works for me with turn on the option for low-security apps.

How about yours?  Please check it and provide relative info. Here's the [LINK](https://support.google.com/accounts/answer/6010255?hl=en).

**Comment by iankuan** [comment]
Also reference to StackOverflow
[Login credentials not working with Gmail SMTP](https://stackoverflow.com/questions/16512592/login-credentials-not-working-with-gmail-smtp)

**Comment by s8w1e2ep** [comment]
Thx, my problem is solved by method of you mention.
BTW, if your gmail account have two-stage verification, you can solve by [link](https://support.google.com/accounts/answer/185833)
